//go:build darwin

package platform

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

const (
	darwinLabel    = "org.feivpn.daemon"
	darwinPlistDir = "/Library/LaunchDaemons"
)

func darwinPlistPath() string { return filepath.Join(darwinPlistDir, darwinLabel+".plist") }

// DarwinAdapter implements Adapter via launchd (LaunchDaemon).
type DarwinAdapter struct{}

func NewDarwin() Adapter { return &DarwinAdapter{} }

func (d *DarwinAdapter) Name() string { return "launchd" }

const darwinPlistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by feivpnctl. DO NOT EDIT BY HAND. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{{.Label}}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{{.BinPath}}</string>
{{- range .Args }}
    <string>{{.}}</string>
{{- end }}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>StandardOutPath</key>
  <string>{{.LogFile}}</string>
  <key>StandardErrorPath</key>
  <string>{{.LogFile}}</string>
  <key>WorkingDirectory</key>
  <string>{{.WorkingDir}}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin</string>
  </dict>
</dict>
</plist>
`

type darwinTplData struct {
	Label      string
	BinPath    string
	Args       []string
	LogFile    string
	WorkingDir string
}

func (d *DarwinAdapter) InstallService(opts InstallOptions) error {
	if opts.BinPath == "" {
		return fmt.Errorf("InstallService: BinPath required")
	}
	if opts.WorkingDir == "" {
		opts.WorkingDir = "/opt/feivpn"
	}
	if opts.LogFile == "" {
		opts.LogFile = "/var/log/feivpn/feivpn.log"
	}
	args := opts.Args
	if opts.ConfigPath != "" {
		args = append([]string{"-c", opts.ConfigPath}, args...)
	}

	if err := os.MkdirAll(filepath.Dir(opts.LogFile), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(darwinPlistDir, 0o755); err != nil {
		return err
	}

	tmpl := template.Must(template.New("plist").Parse(darwinPlistTemplate))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, darwinTplData{
		Label:      darwinLabel,
		BinPath:    opts.BinPath,
		Args:       args,
		LogFile:    opts.LogFile,
		WorkingDir: opts.WorkingDir,
	}); err != nil {
		return err
	}
	if err := os.WriteFile(darwinPlistPath(), buf.Bytes(), 0o644); err != nil {
		return err
	}
	if err := exec.Command("chown", "root:wheel", darwinPlistPath()).Run(); err != nil {
		return fmt.Errorf("chown plist: %w", err)
	}
	return nil
}

func (d *DarwinAdapter) EnableAndStart() error {
	// `launchctl bootstrap` is the modern equivalent of `load -w`.
	if err := launchctl("bootstrap", "system", darwinPlistPath()); err != nil &&
		!strings.Contains(err.Error(), "service already loaded") &&
		!strings.Contains(err.Error(), "Bootstrap failed: 5: Input/output error") {
		return err
	}
	return launchctl("kickstart", "-k", "system/"+darwinLabel)
}

func (d *DarwinAdapter) Stop() error {
	if err := launchctl("bootout", "system/"+darwinLabel); err != nil &&
		!strings.Contains(err.Error(), "Could not find specified service") {
		return err
	}
	return nil
}

func (d *DarwinAdapter) Disable() error {
	if err := launchctl("disable", "system/"+darwinLabel); err != nil &&
		!strings.Contains(err.Error(), "Could not find specified service") {
		return err
	}
	return nil
}

func (d *DarwinAdapter) Uninstall() error {
	_ = d.Stop()
	_ = d.Disable()
	if err := os.Remove(darwinPlistPath()); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func (d *DarwinAdapter) IsActive() (bool, error) {
	out, _ := exec.Command("launchctl", "print", "system/"+darwinLabel).CombinedOutput()
	return strings.Contains(string(out), "state = running"), nil
}

func launchctl(args ...string) error {
	out, err := exec.Command("launchctl", args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("launchctl %s: %w (%s)", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}
