//go:build linux

package platform

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

const (
	linuxUnitName       = "feivpn.service"
	linuxUnitPath       = "/etc/systemd/system/feivpn.service"
	linuxRouterUnitName = "feivpn-router.service"
	linuxRouterUnitPath = "/etc/systemd/system/feivpn-router.service"
)

// LinuxAdapter implements Adapter via systemd.
type LinuxAdapter struct{}

// NewLinux constructs the Linux systemd adapter.
func NewLinux() Adapter { return &LinuxAdapter{} }

func (l *LinuxAdapter) Name() string { return "systemd" }

const linuxUnitTemplate = `# Generated by feivpnctl. DO NOT EDIT BY HAND.
# Re-run "feivpnctl ensure-ready" to regenerate this file.
[Unit]
Description=FeiVPN Daemon (tun2socks user-level)
After=network-online.target feivpn-router.service
Wants=network-online.target
Requires=feivpn-router.service

[Service]
Type=simple
ExecStart={{.BinPath}}{{range .Args}} {{.}}{{end}}
ExecStopPost={{.BinPath}} --recover
WorkingDirectory={{.WorkingDir}}
Restart=on-failure
RestartSec=3
LimitNOFILE=65536
StandardOutput=append:{{.LogFile}}
StandardError=append:{{.LogFile}}
{{- if .User }}
User={{.User}}
{{- end }}

# TUN/route/DNS hijack requires CAP_NET_ADMIN. Easier to just run as root
# for the MVP; we'll trim privileges later via AmbientCapabilities.
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=false

[Install]
WantedBy=multi-user.target
`

// linuxRouterUnitTemplate is the privileged C++ controller. It owns the
// route table + resolv.conf and exposes a unix socket the user-level
// feivpn daemon talks to.
const linuxRouterUnitTemplate = `# Generated by feivpnctl. DO NOT EDIT BY HAND.
# Re-run "feivpnctl ensure-ready" to regenerate this file.
[Unit]
Description=FeiVPN Privileged Router (route + DNS controller)
After=network-online.target
Wants=network-online.target
# This unit is the privilege boundary: it must outlive the user daemon
# until --recover has restored the original routes.
DefaultDependencies=yes

[Service]
Type=simple
ExecStart={{.BinPath}}{{range .Args}} {{.}}{{end}}
WorkingDirectory={{.WorkingDir}}
Restart=on-failure
RestartSec=3
LimitNOFILE=65536
StandardOutput=append:{{.LogFile}}
StandardError=append:{{.LogFile}}
# Always root: route table mutation + /etc/resolv.conf rewrite
User=root
Group=root
RuntimeDirectory=feivpn
RuntimeDirectoryMode=0755

[Install]
WantedBy=multi-user.target
`

func (l *LinuxAdapter) InstallService(opts InstallOptions) error {
	if opts.BinPath == "" {
		return fmt.Errorf("InstallService: BinPath required")
	}
	if opts.WorkingDir == "" {
		opts.WorkingDir = "/opt/feivpn"
	}
	if opts.LogFile == "" {
		opts.LogFile = "/var/log/feivpn/feivpn.log"
	}
	if opts.ConfigPath != "" {
		opts.Args = append([]string{"-config", opts.ConfigPath}, opts.Args...)
	}
	for i := range opts.Args {
		opts.Args[i] = quoteSystemdArg(opts.Args[i])
	}

	tmpl := template.Must(template.New("unit").Parse(linuxUnitTemplate))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, opts); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(opts.LogFile), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(linuxUnitPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(linuxUnitPath, buf.Bytes(), 0o644); err != nil {
		return err
	}
	return systemctl("daemon-reload")
}

func (l *LinuxAdapter) EnableAndStart() error {
	if err := systemctl("enable", linuxUnitName); err != nil {
		return err
	}
	return systemctl("restart", linuxUnitName)
}

func (l *LinuxAdapter) Stop() error {
	if err := systemctl("stop", linuxUnitName); err != nil && !isNotLoaded(err) {
		return err
	}
	return nil
}

func (l *LinuxAdapter) Disable() error {
	if err := systemctl("disable", linuxUnitName); err != nil && !isNotLoaded(err) {
		return err
	}
	return nil
}

func (l *LinuxAdapter) Uninstall() error {
	_ = l.Stop()
	_ = l.Disable()
	if err := os.Remove(linuxUnitPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return systemctl("daemon-reload")
}

func (l *LinuxAdapter) IsActive() (bool, error) {
	cmd := exec.Command("systemctl", "is-active", linuxUnitName)
	out, _ := cmd.CombinedOutput()
	return strings.TrimSpace(string(out)) == "active", nil
}

// ----- router (FeiVPNProxyController) lifecycle -----

func (l *LinuxAdapter) InstallRouterService(opts RouterInstallOptions) error {
	if opts.BinPath == "" {
		return fmt.Errorf("InstallRouterService: BinPath required")
	}
	if opts.WorkingDir == "" {
		opts.WorkingDir = "/opt/feivpn"
	}
	if opts.LogFile == "" {
		opts.LogFile = "/var/log/feivpn/router.log"
	}

	tmpl := template.Must(template.New("router-unit").Parse(linuxRouterUnitTemplate))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, opts); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(opts.LogFile), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(linuxRouterUnitPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(linuxRouterUnitPath, buf.Bytes(), 0o644); err != nil {
		return err
	}
	return systemctl("daemon-reload")
}

func (l *LinuxAdapter) EnableAndStartRouter() error {
	if err := systemctl("enable", linuxRouterUnitName); err != nil {
		return err
	}
	return systemctl("restart", linuxRouterUnitName)
}

func (l *LinuxAdapter) StopRouter() error {
	if err := systemctl("stop", linuxRouterUnitName); err != nil && !isNotLoaded(err) {
		return err
	}
	return nil
}

func (l *LinuxAdapter) DisableRouter() error {
	if err := systemctl("disable", linuxRouterUnitName); err != nil && !isNotLoaded(err) {
		return err
	}
	return nil
}

func (l *LinuxAdapter) UninstallRouter() error {
	_ = l.StopRouter()
	_ = l.DisableRouter()
	if err := os.Remove(linuxRouterUnitPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return systemctl("daemon-reload")
}

func (l *LinuxAdapter) IsRouterActive() (bool, error) {
	cmd := exec.Command("systemctl", "is-active", linuxRouterUnitName)
	out, _ := cmd.CombinedOutput()
	return strings.TrimSpace(string(out)) == "active", nil
}

// ----- helpers -----

func systemctl(args ...string) error {
	cmd := exec.Command("systemctl", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl %s: %w (%s)", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

func isNotLoaded(err error) bool {
	return err != nil && (strings.Contains(err.Error(), "not loaded") || strings.Contains(err.Error(), "could not be found"))
}

func quoteSystemdArg(v string) string {
	// systemd performs % specifier expansion in ExecStart. Double it so
	// literal '%' in access keys / URLs survives as-is.
	v = strings.ReplaceAll(v, "%", "%%")
	// Quote to keep one logical argv item even when the value contains
	// spaces, JSON punctuation, or shell-looking characters.
	return strconv.Quote(v)
}
